FROM node:alpine

RUN apk update && apk upgrade

RUN set -uex ;\
    npm install -g @angular/cli@latest;\
    npm install -g @angular/compiler-cli@latest

RUN mkdir -p /usr/src/app

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN npm install

RUN ng build