version: '2'

services:

  api-test:
    build:
      context: .
      dockerfile: ./tools/Dockerfile-sbt
    volumes:
      - ./:/app
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
      - ~/.m2:/root/.m2
    command: sbt "project affin-api" "~run"
    ports:
      - 9000:9000
    links:
      - rabbitmq-test:rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SBT_OPTS=-Dfile.encoding=UTF-8 -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC
    tty: true
    stdin_open: true

  rabbitmq-test:
    image: rabbitmq:3