version: '2'

services:

  api-base:
    build:
      context: .
      dockerfile: ./tools/Dockerfile-sbt
    volumes:
      - ./:/app
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
      - ~/.m2:/root/.m2
    environment:
      - RABBITMQ_URL=amqp://dev:dev@rabbitmq:5672

  api-dev:
    extends: api-base
    command: sbt "project affin-api" "~run"
    ports:
      - 9000:9000
    links:
      - rabbitmq-dev:rabbitmq
    environment:
      - SBT_OPTS=-Dfile.encoding=UTF-8 -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC
    tty: true
    stdin_open: true

  rabbitmq-dev:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev